#!/usr/bin/env python3

# ROS 2 Python client library
import rclpy
from rclpy.node import Node

# Standard ROS velocity command message
from geometry_msgs.msg import Twist

# Import the custom HTTP API wrapper for the Frodo / EarthRover robot
from asyncvla_ros.driving_control import DrivingController


class FrodoDriverNode(Node):
    def __init__(self):
        # Initialise this ROS 2 node with the name "frodo_driver_node"
        super().__init__('frodo_driver_node')

        # -----------------------------
        # Parameters
        # -----------------------------
        # Base URL of the robot control API
        # Default assumes the robot hosts its API at 192.168.11.1
        self.declare_parameter('base_url', 'http://192.168.11.1')

        # Maximum speed scaling parameter
        # This is declared now for future use, although the current code
        # only clamps commands to [-1, 1] and does not yet actively scale by max_speed
        self.declare_parameter('max_speed', 1.0)

        # Read parameter values
        base_url = self.get_parameter('base_url').value
        self.max_speed = float(self.get_parameter('max_speed').value)

        # -----------------------------
        # Robot API
        # -----------------------------
        # Create the HTTP control client that sends commands to the robot
        self.robot = DrivingController(base_url=base_url)

        # -----------------------------
        # Subscriber
        # -----------------------------
        # Subscribe to the ROS velocity command topic /cmd_vel
        # This topic is expected to contain Twist messages generated by your controller
        self.subscription = self.create_subscription(
            Twist,
            '/cmd_vel',
            self.cmd_callback,
            10
        )

        # Log startup message
        self.get_logger().info('Frodo Driver Node started')

    def cmd_callback(self, msg: Twist):
        # Extract ROS command velocities
        # linear.x = forward/backward speed
        # angular.z = turning speed
        v = msg.linear.x
        w = msg.angular.z

        # -----------------------------
        # Convert ROS cmd_vel -> robot joystick API
        # -----------------------------
        # The robot HTTP API expects:
        #   x = left / right turning command
        #   y = forward / backward command
        #
        # Important convention from the robot API:
        #   negative y = forward
        #   positive y = backward
        #
        # So we map:
        #   ROS forward velocity v  -> API y = -v
        #   ROS angular velocity w  -> API x = w
        y = -v
        x = w

        # Clamp values into the valid joystick range expected by the API
        # The API accepts values from -1.0 to 1.0
        x = max(-1.0, min(1.0, x))
        y = max(-1.0, min(1.0, y))

        # Send the converted command to the robot
        try:
            self.robot.send_control(x, y)

        # If the HTTP request fails, log the error instead of crashing the node
        except Exception as e:
            self.get_logger().error(f'Failed to send command: {e}')


def main(args=None):
    # Start the ROS client library
    rclpy.init(args=args)

    # Create the node
    node = FrodoDriverNode()

    # Keep the node running so it can continuously receive /cmd_vel commands
    rclpy.spin(node)

    # Clean shutdown
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()