#!/usr/bin/env python3
import sys
sys.path = [p for p in sys.path if '/miniconda3/envs/' not in p or '/asyncvla/' in p]
sys.path.insert(0, '/vla_storage/capstone/code/asyncvla/AsyncVLA')
from async_vla.sys1 import main
sys.exit(main())
